PackageName: "MUMPS"
PackageOwner: "JuliaSmoothOptimizers"
PackageUUID: "55d2b088-9f4e-11e9-26c0-150b02ea6a46"
_src_path: "https://github.com/JuliaSmoothOptimizers/JSOBestieTemplate.jl"
_commit: "v0.13.0"
AddBreakage: true
AddBenchmark: false
AddBenchmarkCI: true
