name: CI-Homebrew
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        version: ['1.6', '1']
        os: [ubuntu-latest, macOS-latest]
        arch: [x64]
        allow_failure: [false]
        include:
          - version: 'nightly'
            os: ubuntu-latest
            arch: x64
            allow_failure: true
          - version: 'nightly'
            os: macOS-latest
            arch: x64
            allow_failure: true
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install MUMPS from Homebrew
        id: set-up-mumps
        run: |
          brew tap brewsci/num
          brew tap dpo/mumps-jl
          brew install gcc openblas cmake
          brew install mpich-mumps
          echo "$(brew --prefix)/bin" >> $GITHUB_PATH
          echo "::set-output name=prefix::$(brew --prefix)"
          echo "::set-output name=gfortran::$(which gfortran)"
          echo "::set-output name=mpif90::$(which mpif90)"
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
        env:
          MUMPS_PREFIX: "${{steps.set-up-mumps.outputs.prefix}}/opt/mpich-mumps"
          SCALAPACK_PREFIX: "${{steps.set-up-mumps.outputs.prefix}}/opt/mpich-scalapack"
          JULIA_MPI_PATH: "${{steps.set-up-mumps.outputs.prefix}}/opt/mpich"
          JULIA_MPI_Fortran_COMPILER: "${{steps.set-up-mumps.outputs.mpif90}}"
          FC: "${{steps.set-up-mumps.outputs.prefix}}/opt/gcc/bin/gfortran"
      - uses: julia-actions/julia-runtest@v1
        env:
          JULIA_MPI_PATH: "${{steps.set-up-mumps.outputs.prefix}}/opt/mpich"
          JULIA_MPI_Fortran_COMPILER: "${{steps.set-up-mumps.outputs.mpif90}}"
          FC: "${{steps.set-up-mumps.outputs.prefix}}/opt/gcc/bin/gfortran"
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
